"""create user_library table

Revision ID: 6553586f4478
Revises: b9884646d990
Create Date: 2026-01-22 18:39:00.963843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6553586f4478'
down_revision = 'b9884646d990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('user_library',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_isbn', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_library')
    op.drop_table('book')
    # ### end Alembic commands ###
