"""empty message

Revision ID: 59ce9fb7c64c
Revises: 
Create Date: 2026-02-03 22:59:12.116972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ce9fb7c64c'
down_revision = 'initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_created_by_id_fkey'), type_='foreignkey')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_avatar', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_avatar')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('event_created_by_id_fkey'), 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###
